import 'package:hive/hive.dart';

part 'video_model.g.dart';  // This part file will be generated by Hive

@HiveType(typeId: 1)
class Video {
  @HiveField(0)
  final String iso6391;

  @HiveField(1)
  final String iso31661;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String key;

  @HiveField(4)
  final String site;

  @HiveField(5)
  final int size;

  @HiveField(6)
  final String type;

  @HiveField(7)
  final bool official;

  @HiveField(8)
  final String publishedAt;

  @HiveField(9)
  final String id;

  Video({
    required this.iso6391,
    required this.iso31661,
    required this.name,
    required this.key,
    required this.site,
    required this.size,
    required this.type,
    required this.official,
    required this.publishedAt,
    required this.id,
  });

  factory Video.fromJson(Map<String, dynamic> json) {
    return Video(
      iso6391: json['iso_639_1'],
      iso31661: json['iso_3166_1'],
      name: json['name'],
      key: json['key'],
      site: json['site'],
      size: json['size'],
      type: json['type'],
      official: json['official'],
      publishedAt: json['published_at'],
      id: json['id'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'iso_639_1': iso6391,
      'iso_3166_1': iso31661,
      'name': name,
      'key': key,
      'site': site,
      'size': size,
      'type': type,
      'official': official,
      'published_at': publishedAt,
      'id': id,
    };
  }
}
